# Generated by Django 2.2.10 on 2020-07-07 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя опроса')),
                ('start_date', models.DateTimeField(verbose_name='Начало опроса')),
                ('end_date', models.DateTimeField(verbose_name='Окончание опроса')),
                ('status', models.CharField(max_length=100, verbose_name='статус Опроса')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('type_of', models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('checkbox', 'checkbox')], max_length=20, verbose_name='Тип вопроса')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Interview', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Question', verbose_name='Опрос')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Респондент')),
            ],
        ),
    ]
