# Generated by Django 2.2.10 on 2020-07-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0002_auto_20200707_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='end_date',
            field=models.DateTimeField(blank=True, verbose_name='Окончание опроса'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='start_date',
            field=models.DateTimeField(blank=True, verbose_name='Начало опроса'),
        ),
    ]
